MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  TRAIN_STAGE: 1              # 当前运行阶段一
  PROMPT_LENGTH: 4            # M=4
  ID_LOSS_WEIGHT : 1.0
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_ID_WEIGHT : 1.0         # L_Guide
  I2T_CLOTH_SC_WEIGHT : 1.0   # L_sc
  I2T_CLOTH_ORTHO_WEIGHT : 0.05 # L_de

INPUT:
  SIZE_TRAIN: [384, 192]
  SIZE_TEST: [384, 192]
  PROB: 0.5
  RE_PROB: 0.7
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('prcc')
  ROOT_DIR: '/root/autodl-tmp/CCReID/data'
  LLAVA_JSON_PATH: '/root/autodl-tmp/CCReID/data/prcc_qwen2_final_labels.json'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  STAGE1_MAX_EPOCHS: 5 # 120
  STAGE1_BASE_LR: 0.00035

  STAGE2_MAX_EPOCHS: 3 # 40或50
  STAGE2_BASE_LR: 0.000005
  STAGE2_WARMUP_EPOCHS: 1 #10
  CHECKPOINT_PERIOD: 5 # 20
  IMS_PER_BATCH: 64
  OPTIMIZER_NAME: "AdamW"
  STEPS: [20, 30]
  GAMMA: 0.1
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: True

OUTPUT_DIR: './logs/exp_two_stage'